services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    user: root
    ports:
      - '8000:8000'
    volumes:
      - dynamodb-data:/data

volumes:
  dynamodb-data:
